language: node_js
node_js:
  - 10
cache: npm

install:
  - npm install

branches:
  only:
    - master

script:
  - npm run test
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run affected:build:pr; fi'

before_deploy:
  - git config --global user.email ${GITHUB_EMAIL}
  - git config --global user.name ${GITHUB_USER}
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/gauravsoni119/flair.git" > /dev/null 2>&1
  - git reset --hard HEAD
  - git checkout master
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  provider: script
  script: npm run publish:libs
  skip_cleanup: true
